git:
  commitMessage: 'chore: release v${version}'
github:
  release: true
  releaseName: 'v${version}'
hooks:
  after:init: yarn test:ci
plugins:
  '@release-it/conventional-changelog':
    preset: angular
